name: rawg_sdk_dart
description: A Flutter package to interact with RAWG API written in pure Dart. Both for iOS and Android. It will help you to request games from the RAWG catalog.
version: 0.0.2
homepage: "https://github.com/quetool/rawg_sdk_dart"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
